#
# 服务器-配置
server:
  # 端口
  port: 10301
#
# 日志 配置
#
logging:
  # 日志等级
  level:
    cn.com.xuxiaowei: debug
    # Spring Cloud 中无法使用 logging.level.web: debug
    org.springframework.web: debug
    org.springframework.security: debug
#
# 加密配置
encrypt:
  key-store:
    # keytool -genkeypair -alias xuxiaowei-alias -keyalg RSA -validity 3650 -keystore xuxiaowei.jks -storepass xuxiaowei-storepass -dname "CN=徐晓伟,OU=徐晓伟工作室,O=徐晓伟工作室,L=青岛,ST=山东,C=CH"
    # 密钥口令和密钥库口令相同（否则可能验证失败）
    location: classpath:/xuxiaowei.jks
    alias: xuxiaowei-alias
    password: xuxiaowei-storepass
